<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>MVC app</title>
</head>
<body>
    
    <a href="/index.php">Home</a>
    <a href="/index.php?controller=book&action=index">Books</a>
    <a href="/index.php?controller=default&action=feedback">Contact us</a>
    
    <hr>
    
    <?=$content ?>
    
</body>
</html>