<h1>Contact us</h1>

<form method='post'>
    <input 
        type="email" 
        name="email" 
        class="form-control" 
        placeholder="email"
        value="<?=$form->email ?>"
    > <br>
    
    <textarea 
        name="message" 
        class="form-control" 
        placeholder="message"><?=$form->message ?></textarea><br>
        
    <button class="btn btn-primary">Go</button>
</form>