<h1>Books</h1>


<div class='row'>
    <?php foreach ($books as $book) : ?>
        <div class='col-md-4'>
            
            <div class="card" style="height: 200px; margin-top: 10px">
              <!--<img class="card-img-top" src="..." alt="Card image cap">-->
              <div class="card-body">
                <h4 class="card-title"><?=$book->getTitle() ?></h4>
                <p class="card-text"><?=$book->getPrice() ?></p>
                <a href="/index.php?controller=cart&amp;action=addToCart&amp;id=<?=$book->getId() ?>" class="btn btn-primary">Add to cart</a>
                <a href="/index.php?controller=book&amp;action=show&amp;id=<?=$book->getId() ?>" class="btn btn-success">Details</a>
              </div>
            </div>
            
        </div>
    <?php endforeach; ?>
</div>



